name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^3.0.0

  # iOS-style icons
  cupertino_icons: ^1.0.8


  http: ^1.1.0

    # State management
  provider: ^6.1.2

  # HTTP client
  dio: ^5.7.0

  # Secure local storage for JWT
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
