name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  http: ^1.1.0
  provider: ^6.1.2
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg

# Splash screen configuration
flutter_native_splash:
  color: 0xFFFFFFFF          # white background
  image: assets/logo.jpg      # your logo path
  android: true
  ios: true


